/*==================================================================================================
*   Project              : RTD AUTOSAR 4.9
*   Platform             : CORTEXM
*   Peripheral           : generic
*   Dependencies         : 
*
*   Autosar Version      : 4.9.0
*   Autosar Revision     : ASR_REL_4_9_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 7.0.1
*   Build Version        : S32K3_RTD_7_0_1_D2602_ASR_REL_4_9_REV_0000_20260206
*
*   Copyright 2020 - 2026 NXP
*
*   NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be 
*   used strictly in accordance with the applicable license terms. By expressly 
*   accepting such terms or by downloading, installing, activating and/or otherwise 
*   using the software, you are agreeing that you have read, and that you agree to 
*   comply with and are bound by, such license terms. If you do not agree to be 
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/


#ifndef CANIF_CFG_H
#define CANIF_CFG_H

/**
*   @file    CanIf_Cfg.h
*   @version 7.0.1
*
*   @brief   AUTOSAR CanIf - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CANIF_DRIVER
*   @{
*/

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "CanIf_PBcfg.h"
/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define CANIF_VENDOR_ID_CFG_H                     43
#define CANIF_MODULE_ID_CFG_H                     60
#define CANIF_AR_RELEASE_MAJOR_VERSION_CFG_H      4
#define CANIF_AR_RELEASE_MINOR_VERSION_CFG_H      9
#define CANIF_AR_RELEASE_REVISION_VERSION_CFG_H   0
#define CANIF_SW_MAJOR_VERSION_CFG_H              7
#define CANIF_SW_MINOR_VERSION_CFG_H              0
#define CANIF_SW_PATCH_VERSION_CFG_H              1
/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
/* Check if header file and CanIf_PBcfg.h configuration header file are of the same vendor */
#if (CANIF_VENDOR_ID_PBCFG_H != CANIF_VENDOR_ID_CFG_H)
#error "CanIf_PBcfg.h and CanIf_Cfg.h have different vendor IDs"
#endif
/* Check if header file and CanIf_PBcfg.h configuration header file are of the same Autosar version */
#if ((CANIF_AR_RELEASE_MAJOR_VERSION_PBCFG_H != CANIF_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
(CANIF_AR_RELEASE_MINOR_VERSION_PBCFG_H != CANIF_AR_RELEASE_MINOR_VERSION_CFG_H) || \
(CANIF_AR_RELEASE_REVISION_VERSION_PBCFG_H != CANIF_AR_RELEASE_REVISION_VERSION_CFG_H) \
    )
#error "AutoSar Version Numbers of CanIf_PBcfg.h and CanIf_Cfg.h are different"
#endif
/* Check if header file and CanIf_PBcfg.h configuration header file are of the same software version */
#if ((CANIF_SW_MAJOR_VERSION_PBCFG_H != CANIF_SW_MAJOR_VERSION_CFG_H) || \
(CANIF_SW_MINOR_VERSION_PBCFG_H != CANIF_SW_MINOR_VERSION_CFG_H) || \
(CANIF_SW_PATCH_VERSION_PBCFG_H != CANIF_SW_PATCH_VERSION_CFG_H) \
    )
#error "Software Version Numbers of CanIF_PBcfg.h and CanIf_Cfg.h are different"
#endif
/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
/**
*   @brief      Number of CAN drivers is referenced
*/
#define CANIF_NUM_CANDRV_USED (1U)
/**
*   @brief      Number of CanIf controller
*/
#define CANIF_CONTROLLER_CONFIG_COUNT (1U)
/**
*   @brief      Enable/Disable Development Error Detection and Notification
*/
#define CANIF_DEV_ERROR_DETECT (STD_ON)
/**
*   @brief      Enable/Disable Wakeup Support
*/
#define CANIF_WAKEUP_SUPPORT (STD_ON)
/**
*   @brief      Module instance of the CanIf driver
*/
#define CANIF_INSTANCE  ((uint8)0U)
/**
*   @brief      Enable/Disable Precompile Support
*/
#define CANIF_PRECOMPILE_SUPPORT (STD_ON)

/* Symbolic name for CanIfTxPduCfg_INVERTOR_STANGA */
#define CanIfTxPduCfg_INVERTOR_STANGA    ((PduIdType)0U)

/* Symbolic name for CanIfTxPduCfg_INVERTOR_DREAPTA */
#define CanIfTxPduCfg_INVERTOR_DREAPTA    ((PduIdType)1U)

/* Symbolic name for CanIfTxPduCfg_INVERTOARE */
#define CanIfTxPduCfg_INVERTOARE    ((PduIdType)2U)

/* Symbolic name for CanIfTxPduCfg_BORD */
#define CanIfTxPduCfg_BORD    ((PduIdType)3U)

/* Symbolic name for CanIfTxPduCfg_ACCELERATIE */
#define CanIfTxPduCfg_ACCELERATIE    ((PduIdType)4U)

/* Symbolic name for CanIfTxPduCfg_FRANA */
#define CanIfTxPduCfg_FRANA    ((PduIdType)5U)

/* Symbolic name for CanIfTxPduCfg_BATERIE */
#define CanIfTxPduCfg_BATERIE    ((PduIdType)6U)

/* Symbolic name for CanIfTxPduCfg_BATERIE_TENSIUNI_CELULE */
#define CanIfTxPduCfg_BATERIE_TENSIUNI_CELULE    ((PduIdType)7U)

/* Symbolic name for CanIfTxPduCfg_BATERIE_TEMPERATURI_CELULE */
#define CanIfTxPduCfg_BATERIE_TEMPERATURI_CELULE    ((PduIdType)8U)

/* Symbolic name for CanIfTxPduCfg_BATERIE_2 */
#define CanIfTxPduCfg_BATERIE_2    ((PduIdType)9U)

/* Symbolic name for CanIfTxPduCfg_BATERIE_CHARGER */
#define CanIfTxPduCfg_BATERIE_CHARGER    ((PduIdType)10U)

/* Symbolic name for CanIfTxPduCfg_COMUNICATII */
#define CanIfTxPduCfg_COMUNICATII    ((PduIdType)11U)

/* Symbolic name for CanIfRxPduCfg_INVERTOR_STANGA */
#define CanIfRxPduCfg_INVERTOR_STANGA    ((PduIdType)0U)

/* Symbolic name for CanIfRxPduCfg_INVERTOR_DREAPTA */
#define CanIfRxPduCfg_INVERTOR_DREAPTA    ((PduIdType)1U)

/* Symbolic name for CanIfRxPduCfg_INVERTOARE */
#define CanIfRxPduCfg_INVERTOARE    ((PduIdType)2U)

/* Symbolic name for CanIfRxPduCfg_BORD */
#define CanIfRxPduCfg_BORD    ((PduIdType)3U)

/* Symbolic name for CanIfRxPduCfg_ACCELERATIE */
#define CanIfRxPduCfg_ACCELERATIE    ((PduIdType)4U)

/* Symbolic name for CanIfRxPduCfg_FRANA */
#define CanIfRxPduCfg_FRANA    ((PduIdType)5U)

/* Symbolic name for CanIfRxPduCfg_BATERIE */
#define CanIfRxPduCfg_BATERIE    ((PduIdType)6U)

/* Symbolic name for CanIfRxPduCfg_BATERIE_TENSIUNI_CELULE */
#define CanIfRxPduCfg_BATERIE_TENSIUNI_CELULE    ((PduIdType)7U)

/* Symbolic name for CanIfRxPduCfg_BATERIE_TEMPERATURI_CELULE */
#define CanIfRxPduCfg_BATERIE_TEMPERATURI_CELULE    ((PduIdType)8U)

/* Symbolic name for CanIfRxPduCfg_BATERIE_2 */
#define CanIfRxPduCfg_BATERIE_2    ((PduIdType)9U)

/* Symbolic name for CanIfRxPduCfg_BATERIE_CHARGER */
#define CanIfRxPduCfg_BATERIE_CHARGER    ((PduIdType)10U)

/* Symbolic name for CanIfRxPduCfg_COMUNICATII */
#define CanIfRxPduCfg_COMUNICATII    ((PduIdType)11U)

#define CANIF_CONFIG_EXT

#ifdef __cplusplus
}
#endif

/** @} */

#endif /* _CANIF_CFG_H_ */

